name: Create and Upload Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create release archives
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAR_FILENAME=cpp-oasvalidator-${TAG}.tar.gz
          ZIP_FILENAME=cpp-oasvalidator-${TAG}.zip
          # Create tar.gz archive
          git archive --format=tar.gz --prefix=cpp-oasvalidator-${TAG}/ -o $TAR_FILENAME ${TAG}
          # Create zip archive
          git archive --format=zip --prefix=cpp-oasvalidator-${TAG}/ -o $ZIP_FILENAME ${TAG}
          
          # Include submodules
          TEMP_DIR=$(mktemp -d)
          git clone --recursive . $TEMP_DIR/cpp-oasvalidator-${TAG}
          
          # Add submodule content to tar.gz archive
          tar -czf $TEMP_DIR/cpp-oasvalidator-${TAG}-with-submodules.tar.gz -C $TEMP_DIR cpp-oasvalidator-${TAG}
          mv $TEMP_DIR/cpp-oasvalidator-${TAG}-with-submodules.tar.gz $TAR_FILENAME
          
          # Add submodule content to zip archive
          (cd $TEMP_DIR && zip -r cpp-oasvalidator-${TAG}-with-submodules.zip cpp-oasvalidator-${TAG})
          mv $TEMP_DIR/cpp-oasvalidator-${TAG}-with-submodules.zip $ZIP_FILENAME
          
          # Clean up
          rm -rf $TEMP_DIR

      - name: List created files for debugging
        run: |
          ls -alh
          ls -alh $TAR_FILENAME
          ls -alh $ZIP_FILENAME

      - name: Upload tar.gz to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.MY_PAT }}
          file: ${{ steps.build.outputs.TAR_FILENAME }}
          asset_name: ${{ steps.build.outputs.TAR_FILENAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release ${TAG}"

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.MY_PAT }}
          file: ${{ steps.build.outputs.ZIP_FILENAME }}
          asset_name: ${{ steps.build.outputs.ZIP_FILENAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release ${TAG}"
