name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true # Include submodules
          fetch-depth: 0

      - name: Create tar.gz archive
        run: |
          mkdir -p release/cpp-oasvalidator-${GITHUB_REF#refs/tags/}
          git archive --format=tar.gz --prefix=cpp-oasvalidator-${GITHUB_REF#refs/tags/}/ HEAD | tar -x -C release
          git submodule foreach --recursive 'git archive --format=tar.gz --prefix=cpp-oasvalidator-${GITHUB_REF#refs/tags/}/$path/ HEAD | tar -x -C release'
          cd release
          tar -czf ../cpp-oasvalidator-${GITHUB_REF#refs/tags/}.tar.gz cpp-oasvalidator-${GITHUB_REF#refs/tags/}
          cd ..

      - name: Create zip archive
        run: |
          mkdir -p release/cpp-oasvalidator-${GITHUB_REF#refs/tags/}
          git archive --format=zip --prefix=cpp-oasvalidator-${GITHUB_REF#refs/tags/}/ HEAD -o release/cpp-oasvalidator-${GITHUB_REF#refs/tags/}.zip
          cd release
          unzip cpp-oasvalidator-${GITHUB_REF#refs/tags/}.zip -d .
          rm cpp-oasvalidator-${GITHUB_REF#refs/tags/}.zip
          git submodule foreach --recursive 'git archive --format=zip --prefix=cpp-oasvalidator-${GITHUB_REF#refs/tags/}/$path/ HEAD -o ../$path.zip && unzip ../$path.zip -d . && rm ../$path.zip'
          zip -r ../cpp-oasvalidator-${GITHUB_REF#refs/tags/}.zip cpp-oasvalidator-${GITHUB_REF#refs/tags/}
          cd ..

      - name: Upload Release Assets
        uses: actions/upload-artifact@v2
        with:
          name: release-asset-tar
          path: cpp-oasvalidator-${GITHUB_REF#refs/tags/}.tar.gz

      - name: Upload Release Assets
        uses: actions/upload-artifact@v2
        with:
          name: release-asset-zip
          path: cpp-oasvalidator-${GITHUB_REF#refs/tags/}.zip
