name: Linux Build

on:
  push:
    branches:
      - main
      #- '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cpp-oasvalidator
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake  lcov gcovr
          sudo apt-get install -y plantuml
          sudo apt-get install -yq doxygen

      - name: Install python dependencies
        run: |
          pip install sphinx breathe exhale furo sphinxcontrib-plantuml

      - name: Build and install libbenchmark
        run: |
          cd ./thirdparty/benchmark
          mkdir build
          cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DCMAKE_BUILD_TYPE=Release ../
          sudo cmake --build "build" --config Release --target install -- -j $(nproc)

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON -DBUILD_PERF=ON -DBUILD_DOCS=ON -DBUILD_EXAMPLE=ON

      - name: Build oasvalidator
        run: cmake --build build --target oasvalidator --config Release -j $(nproc)

      - name: Build oasvalidator-unittests
        run: cmake --build build --target oasvalidator-unittests --config Release -j $(nproc)

      - name: Build oasvalidator-perftests
        run: cmake --build build --target oasvalidator-perftests --config Release -j $(nproc)

      - name: Run oasvalidator-perftests
        run: build/test/perftest/oasvalidator-perftests --benchmark_format=json > build/test/perftest/benchmark.json

      - name: Convert benchmark.json to benchmark.rst
        run: python .github/workflows/convert_json_to_rst.py build/test/perftest/benchmark.json build/docs/benchmark.rst

      - name: Build covhtml-oasvalidator
        run: cmake --build build --target covhtml-oasvalidator --config Release -j $(nproc)

      - name: Build docs
        run: cmake --build build --target docs --config Release -j $(nproc)

      - name: Copy covhtml-oasvalidator to docs
        run: cp -r build/covhtml-oasvalidator build/docs/html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PAT }}
          publish_dir: build/docs/html

      - name: Generate Coverage Report
        if: github.ref == 'refs/heads/main'
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}