name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake  lcov gcovr 
          sudo apt-get install -yq doxygen

      - name: Install python dependencies
        run: |
          pip3 install sphinx breathe exhale furo sphinxcontrib-plantuml

      - name: Install google test
        run: |          
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp ./lib/libgtest*.a /usr/lib

      - name: Clone libbenchmark
        run: git clone https://github.com/google/benchmark.git

      - name: Build libbenchmark
        run: |
          cd benchmark
          cmake -E make_directory "build"
          cmake -E chdir "build" cmake -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release ../
          cmake --build "build" --config Release -- -j $(nproc)

      - name: Install libbenchmark
        run: sudo cmake --build "build" --target install --config Release
        working-directory: ./benchmark

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON -DBUILD_PERF=ON -DBUILD_DOCS=ON -DBUILD_EXAMPLE=ON

      - name: Build oasvalidator
        run: cmake --build build --target oasvalidator --config Release -j $(nproc)

      - name: Build oasvalidator-unittests
        run: cmake --build build --target oasvalidator-unittests --config Release -j $(nproc)

      - name: Build oasvalidator-perftests
        run: cmake --build build --target oasvalidator-perftests --config Release -j $(nproc)

      - name: Run oasvalidator-perftests
        run: build/test/perftest/oasvalidator-perftests --benchmark_format=json > build/test/perftest/benchmark.json

      - name: Convert benchmark.json to benchmark.rst
        run: python .github/workflows/convert_json_to_rst.py build/test/perftest/benchmark.json build/docs/benchmark.rst

      - name: Build covhtml-oasvalidator
        run: cmake --build build --target covhtml-oasvalidator --config Release -j $(nproc)

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Build docs
        run: cmake --build build --target docs --config Release -j $(nproc)

      - name: Copy covhtml-oasvalidator to docs
        run: cp -r build/covhtml-oasvalidator build/docs/html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PAT }}
          publish_dir: build/docs/html

      - name: Generate Coverage Report
        if: github.ref == 'refs/heads/main'
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}